### PR TITLE
Use begin and end with times without date

### PR DESCRIPTION
**Pull request by fluca1978**
A possible implementation for issue #495 .

### CODE REVIEW

**Comment by fluca1978** [comment]
I also suspect it could be easier to either use DateTime (adding a dependency) to check for valid time/datetime values.
At least, splitting the datetime in date + time could help testing and checking for each row, at the cost of two regexp when only one is used.

**Comment by darold** [comment]
Thanks for the patch, you shoul use `"$prefix_vars{'t_hour'}:$prefix_vars{'t_min'}:$prefix_vars{'t_sec'}"` instead of the regexp.
```
if ( $from_hour || $to_hour ){
      $prefix_vars{'t_time'} = $prefix_vars{'t_timestamp'};
      $prefix_vars{'t_time'} =~ s/^(\d{4})-(\d{2})-(\d{2}) //;

      return 1  if ( $from_hour && ( $from_hour gt $prefix_vars{'t_time'} ) );
      return -1 if ( $to_hour   && ( $to_hour   lt $prefix_vars{'t_time'} ) );
  }
```
should be rewritten:
```
if ( $from_hour || $to_hour ){
     my $ltime = "$prefix_vars{'t_hour'}:$prefix_vars{'t_min'}:$prefix_vars{'t_sec'}";
      return 1  if ( $from_hour && ( $from_hour gt $ltime ) );
      return -1 if ( $to_hour   && ( $to_hour   lt $ltime ) );
}
```
Also why have you commented line with the exit call in commit 2996cad?
```
if (!$rebuild && $empty_files) {
	&logmsg('DEBUG', "All log files are empty, exiting...");
	unlink("$PID_FILE");
#	exit 0;
}
```
We must not continue if there is nothing to process.

I will be pleased to apply your PR after these two fixes.

**Comment by fluca1978** [comment]
Thanks, I applied your suggestions and fixed the wrong comment in front of the exit.
Why don't we seta `$prefix_vars{t_time}` already prepared instead of computing it when it is used to filter? Something line `$prefix_vars{t_timestamp}`. Should not be this more consistent (at the expense of one extra var per log line)?

**Comment by darold** [comment]
I agree with your last comment but I don't think will be a gain of performances but it is interressing to bench.

**Pull request merged**
